# Use the official Node.js runtime as the base image
FROM node:16

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the entire application directory to the container
COPY . .

# Expose the port that the application will run on
EXPOSE 3000

# Define the command to start the application
CMD [ "npm", "run", "start" ]
